### ISSUE TITLE
Link "Tabelle" next to Anwesenheiten and Spieler to the match table false 

### ISSUE THREAD

**Issue by Tracker-HM** [netzfisch/teamorga#1]
Please change ...[uid]=45 to ...[uid]=25
It seems to me that the uid-number are the first two numbers of the match numbers.

**Comment by netzfisch** [comment]
I removed that link temporaliy, because the exisiting implemetation would not work for the new "group feature", which I just brought online!

So, now you can create a new group, you will find the link in the backoffice - happy testing!

**Comment by netzfisch** [comment]
With the group feature, that doesn't make sense anymore. Now, you can create wiht markdown a link in the field of private_information by your self!
