### ISSUE TITLE
Columns in Allianz-BSG Eventlist not in a row

### ISSUE THREAD

**Issue by Tracker-HM** [netzfisch/teamorga#10]
I don't know why but all delete-columns recurrences in ATSV are in in row:
delete: <date1>?
delete: <date2>?
delete: <date3>?

In the group Allianz-BSG the delete-columns are something like this:
delete: <date1>? delete: 
<date2>? delete: <date3>?

In both groups there a reccurences with long and short categorys. The same with place and remark. At the moment i can't see a reason for this behaviour.

**Comment by netzfisch** [comment]
its because of
- flexible table widths design and 
- in the case of 'ATSV', there are other rows with wider column text, which reduces the left space for the date column

If you scroll up and down, than you will spot some text 'boxing other columns' away ...
