### ISSUE TITLE
Double entry of André

### ISSUE THREAD

**Issue by Tracker-HM** [netzfisch/teamorga#12]
André: Yes and No for 30.11.

**Comment by Tracker-HM** [comment]
As I can see we have only one André in the player/member list.

**Comment by netzfisch** [comment]
that's the second time André somehow managed that! We need to retrace, how he did it!

**Comment by Tracker-HM** [comment]
As he said, he lost his mobile connection while he clicked the link.

**Comment by netzfisch** [comment]
Switched to Unicorn Webserver 181017fd4557cdb806a153e9e46e9fb3457bfc47, which supposed to be more robust concerning these kind of double entries!
