### ISSUE TITLE
Same private information

### ISSUE THREAD

**Issue by Tracker-HM** [netzfisch/teamorga#2]
I had created two new groups. One group with the name Allianz 1 and the other with the name Allianz 2.  This are the real used team names used by the BSG. I entered different private information for each group. But for both groups the displayed private information is the same.

**Comment by Tracker-HM** [comment]
Hmm, after destroying these two groups i create four new groups without the problem above.

**Comment by netzfisch** [comment]
Closing, as it works for me also!
