### ISSUE TITLE
Terminverschiebung

### ISSUE THREAD

**Issue by Tracker-HM** [netzfisch/teamorga#4]
Beim Betriebssport werden notwendigerweise häufiger mal Punktspieltermine verschoben. Es wäre daher sehr praktisch und auch sinnvoll, wenn man beim editieren eines schon angelegten Events auch das Datum und nicht nur die Uhrzeit verändern könnte.
Momentan kann man nur den schon angelegten Termin komplett löschen und muss einen neuen Termin mit den gleichen Daten -bis aufs Datum und u.U. Uhrzeit/Ort- wie zuvor anlegen. Das ist IMHO wenig elegant.

**Comment by netzfisch** [comment]
This is caused of the actual data model and bothers me also in other places.

I will switch from todays logic with two tables (events, recurrences) to "single table inheritence" (just events). But at the moment this is priority 2, because I want to get first the multitenancy feature fully working!

**Comment by netzfisch** [comment]
Now it is working, you can move multiple recurrences dates as wished, see 2638889a1dd7e61697502ffe99d7d2c7488d4cf5 :-)
