### ISSUE TITLE
Moving an event from one date to a new one (Allianz BSG).

### ISSUE THREAD

**Issue by Tracker-HM** [netzfisch/teamorga#9]
I moved an event from 14.10.13 to 02.12.13.
- The base date stays the same (14.10.)
- The end date stays the same (14.10.)

I know the reason for this, but i think this could be irritating.

**Comment by Tracker-HM** [comment]
It seems to be working correct even if I move events of a recurrence past or before another event. Base and end date are something like a reference to the original date. Should this be unchanged?
At the moment i think so. :-)

**Comment by netzfisch** [comment]
Your are right, the event base_date and end_date are only used once at the beginning to create the recurrence dates. So I removed them from the views!
